In [1]:
import os
import glob

import json
import pandas as pd

In [2]:
PREDICTION_ROOT = "/mnt/nas/baecm/starcraft-vision/models/predictions"

In [3]:
VANILLA_DIRS = glob.glob(os.path.join(PREDICTION_ROOT, "all_correct*vanilla*fold1*s123*"))
KBRS_DIRS = glob.glob(os.path.join(PREDICTION_ROOT   , "all_correct*fold1*s123*kbrs025*base_score*"))

print(VANILLA_DIRS[0])
print(KBRS_DIRS[0])

/mnt/nas/baecm/starcraft-vision/models/predictions/all_correct_win4_vanilla_fold1_s123_20251201_072032
/mnt/nas/baecm/starcraft-vision/models/predictions/all_correct_win4_kbrs_fold1_s123_kbrs025_base_score_20251219_080334

In [4]:
FILE_PATH = "model_030/*.rep/all_correct.json"

In [5]:
vanilla_json_file = glob.glob(os.path.join(VANILLA_DIRS[0], FILE_PATH))[0]
kbrs_json_file = glob.glob(os.path.join(KBRS_DIRS[0], FILE_PATH))[0]

In [6]:
with open(vanilla_json_file, "r") as f:
    vanilla_json_data = json.load(f)

with open(kbrs_json_file, "r") as f:
    kbrs_json_data = json.load(f)

In [7]:
df_vanilla = pd.DataFrame(vanilla_json_data["annotations"])
df_kbrs = pd.DataFrame(kbrs_json_data["annotations"])

In [8]:
df_vanilla.sort_values(['image_id', 'score'], ascending=[True, False]).drop_duplicates('image_id', keep='first')

,id,image_id,category_id,bbox,score,area,segmentation,iscrowd
0,1,3,1,"[0, 0, 19, 12]",0.796460,228,"[[0, 0, 19, 0, 19, 12, 0, 12]]",0
2,3,4,1,"[0, 0, 19, 12]",0.796460,228,"[[0, 0, 19, 0, 19, 12, 0, 12]]",0
4,5,5,1,"[0, 0, 19, 12]",0.796460,228,"[[0, 0, 19, 0, 19, 12, 0, 12]]",0
6,7,6,1,"[0, 0, 19, 12]",0.796460,228,"[[0, 0, 19, 0, 19, 12, 0, 12]]",0
8,9,7,1,"[0, 0, 19, 12]",0.796460,228,"[[0, 0, 19, 0, 19, 12, 0, 12]]",0
...,...,...,...,...,...,...,...,...
431743,431744,66683,1,"[10, 62, 20, 12]",0.971709,240,"[[10, 62, 30, 62, 30, 74, 10, 74]]",0
431753,431754,66684,1,"[8, 62, 20, 13]",0.968408,260,"[[8, 62, 28, 62, 28, 75, 8, 75]]",0
431762,431763,66685,1,"[5, 61, 20, 13]",0.979587,260,"[[5, 61, 25, 61, 25, 74, 5, 74]]",0
431771,431772,66686,1,"[5, 61, 20, 12]",0.983009,240,"[[5, 61, 25, 61, 25, 73, 5, 73]]",0
431780,431781,66687,1,"[5, 61, 20, 13]",0.985855,260,"[[5, 61, 25, 61, 25, 74, 5, 74]]",0

In [9]:
df_kbrs.sort_values(['image_id', 'score'], ascending=[True, False]).drop_duplicates('image_id', keep='first')

,id,image_id,category_id,bbox,score,area,segmentation,iscrowd
0,1,3,1,"[106, 113, 21, 12]",0.964123,252,"[[106, 113, 127, 113, 127, 125, 106, 125]]",0
2,3,4,1,"[106, 113, 21, 12]",0.964123,252,"[[106, 113, 127, 113, 127, 125, 106, 125]]",0
4,5,5,1,"[106, 113, 21, 12]",0.964123,252,"[[106, 113, 127, 113, 127, 125, 106, 125]]",0
6,7,6,1,"[106, 113, 21, 12]",0.964123,252,"[[106, 113, 127, 113, 127, 125, 106, 125]]",0
8,9,7,1,"[106, 113, 21, 12]",0.964123,252,"[[106, 113, 127, 113, 127, 125, 106, 125]]",0
...,...,...,...,...,...,...,...,...
435530,435531,66683,1,"[5, 61, 20, 13]",0.963811,260,"[[5, 61, 25, 61, 25, 74, 5, 74]]",0
435543,435544,66684,1,"[8, 63, 20, 12]",0.960952,240,"[[8, 63, 28, 63, 28, 75, 8, 75]]",0
435556,435557,66685,1,"[5, 61, 20, 13]",0.966309,260,"[[5, 61, 25, 61, 25, 74, 5, 74]]",0
435569,435570,66686,1,"[5, 61, 20, 13]",0.963659,260,"[[5, 61, 25, 61, 25, 74, 5, 74]]",0
435583,435584,66687,1,"[8, 63, 20, 12]",0.951891,240,"[[8, 63, 28, 63, 28, 75, 8, 75]]",0

In [10]:
df_kbrs.sort_values(['image_id', 'score'], ascending=[True, False]).groupby('image_id').nth(0).describe().T[['mean', 'std']]

                      mean            std
id           202730.920680  123731.803099
image_id      33345.304669   19250.829178
category_id       1.000000       0.000000
score             0.900381       0.098357
area            239.765308       6.942789
iscrowd           0.000000       0.000000

In [11]:
df_kbrs.sort_values(['image_id', 'score'], ascending=[True, False]).groupby('image_id').nth(1).describe().T[['mean', 'std']]

                      mean            std
id           202505.109416  123912.304605
image_id      33308.809209   19279.733580
category_id       1.000000       0.000000
score             0.817502       0.119726
area            239.548075       7.337545
iscrowd           0.000000       0.000000

In [12]:
df_kbrs.sort_values(['image_id', 'score'], ascending=[True, False]).groupby('image_id').nth(2).describe().T[['mean', 'std']]

                      mean            std
id           203360.986083  124505.521365
image_id      33439.427161   19360.477711
category_id       1.000000       0.000000
score             0.742277       0.120621
area            239.531745       6.974845
iscrowd           0.000000       0.000000

In [13]:
df_vanilla.sort_values(['image_id', 'score'], ascending=[True, False]).groupby('image_id').nth(0).describe().T[['mean', 'std']]

                      mean            std
id           205749.052555  124987.353017
image_id      33340.944580   19249.761584
category_id       1.000000       0.000000
score             0.934340       0.077870
area            239.385943       7.589385
iscrowd           0.000000       0.000000

In [14]:
df_vanilla.sort_values(['image_id', 'score'], ascending=[True, False]).groupby('image_id').nth(1).describe().T[['mean', 'std']]

                      mean            std
id           205349.341844  125065.729283
image_id      33279.565309   19261.871669
category_id       1.000000       0.000000
score             0.847829       0.112181
area            239.496443       7.740302
iscrowd           0.000000       0.000000

In [15]:
df_vanilla.sort_values(['image_id', 'score'], ascending=[True, False]).groupby('image_id').nth(2).describe().T[['mean', 'std']]

                      mean            std
id           205154.696398  124890.275440
image_id      33255.311961   19221.096686
category_id       1.000000       0.000000
score             0.766197       0.118287
area            239.481974       7.800961
iscrowd           0.000000       0.000000

In [16]:
##

In [17]:
SCORE_ROOT = "/mnt/nas/baecm/starcraft-vision/results/kbrs_scores"

In [18]:
SCORE_GT_DIRS      = glob.glob(os.path.join(SCORE_ROOT, "gt",   "all_correct"))
SCORE_VANILLA_DIRS = glob.glob(os.path.join(SCORE_ROOT, "pred", "all_correct*vanilla*fold1*s123*"))
SCORE_KBRS_DIRS    = glob.glob(os.path.join(SCORE_ROOT, "pred", "all_correct*fold1*s123*kbrs025*base_score*"))

In [19]:
score_vanilla_path = os.path.join(SCORE_VANILLA_DIRS[0], "model_030", "all_correct", "kbrs_samples_275.json")
with open(score_vanilla_path, "r") as f:
    json_score_vanilla = json.load(f)

In [20]:
score_kbrs_path = os.path.join(SCORE_KBRS_DIRS[0], "model_030", "all_correct", "kbrs_samples_275.json")
with open(score_kbrs_path, "r") as f:
    json_score_kbrs = json.load(f)

In [21]:
score_vanilla = pd.DataFrame(json_score_vanilla).sort_values('image_id')

In [22]:
score_kbrs = pd.DataFrame(json_score_kbrs).sort_values('image_id')

In [23]:
def get_len(x):
    return len(x) if isinstance(x, list) else 1

In [24]:
df_lengths = score_vanilla[['xy', 'density', 'centeredness', 'mixture']].map(get_len)
# 길이가 모두 동일하지 않은 row만 필터링
mismatch = df_lengths[~df_lengths.eq(df_lengths.iloc[:, 0], axis=0).all(axis=1)]

# 4개 컬럼의 길이가 모두 일치하는 행의 인덱스만 추출
is_matching = df_lengths.eq(df_lengths.iloc[:, 0], axis=0).all(axis=1)

# 일치하는 데이터만 필터링 후 explode
score_clean = score_vanilla[is_matching].copy()
df_score_vanilla_exploded = score_clean.explode(['xy', 'density', 'centeredness', 'mixture'])

In [25]:
df_lengths = score_kbrs[['xy', 'density', 'centeredness', 'mixture']].map(get_len)
# 길이가 모두 동일하지 않은 row만 필터링
mismatch = df_lengths[~df_lengths.eq(df_lengths.iloc[:, 0], axis=0).all(axis=1)]

# 4개 컬럼의 길이가 모두 일치하는 행의 인덱스만 추출
is_matching = df_lengths.eq(df_lengths.iloc[:, 0], axis=0).all(axis=1)

# 일치하는 데이터만 필터링 후 explode
score_clean = score_kbrs[is_matching].copy()
df_score_kbrs_exploded = score_clean.explode(['xy', 'density', 'centeredness', 'mixture'])

In [26]:
df_score_vanilla_exploded['density'] = df_score_vanilla_exploded['density'].astype(float)
df_score_vanilla_exploded['centeredness'] = df_score_vanilla_exploded['centeredness'].astype(float)
df_score_vanilla_exploded['mixture'] = df_score_vanilla_exploded['mixture'].astype(float)

In [27]:
df_score_kbrs_exploded['density'] = df_score_kbrs_exploded['density'].astype(float)
df_score_kbrs_exploded['centeredness'] = df_score_kbrs_exploded['centeredness'].astype(float)
df_score_kbrs_exploded['mixture'] = df_score_kbrs_exploded['mixture'].astype(float)

In [28]:
df_score_vanilla_exploded.describe()

,replay_id,image_id,num_anns,density,centeredness,mixture
count,429918.0,429918.000000,429918.000000,429906.000000,429906.000000,429906.000000
mean,275.0,34912.222708,7.524551,0.888959,0.827210,0.240089
std,0.0,19187.910445,2.701064,0.078177,0.100482,0.358815
min,275.0,3.000000,0.000000,0.278809,0.067383,0.000000
25%,275.0,18716.000000,6.000000,0.854980,0.755371,0.000000
50%,275.0,33731.000000,7.000000,0.900391,0.838867,0.000000
75%,275.0,52340.000000,9.000000,0.941406,0.905762,0.478027
max,275.0,66687.000000,23.000000,1.000000,1.000000,1.000000

In [29]:
print(len(df_score_vanilla_exploded.sort_values(['image_id'], ascending=[True]).groupby('image_id').nth(0)))
df_score_vanilla_exploded.sort_values(['image_id'], ascending=[True]).groupby('image_id').nth(0).describe().T[['mean', 'std']]

66350

                      mean           std
replay_id       275.000000      0.000000
image_id      33340.274785  19295.319408
num_anns          6.479367      2.602613
density           0.898274      0.077024
centeredness      0.838693      0.106390
mixture           0.449115      0.397411

In [30]:
print(len(df_score_vanilla_exploded.sort_values(['image_id'], ascending=[True]).groupby('image_id').nth(1)))
df_score_vanilla_exploded.sort_values(['image_id'], ascending=[True]).groupby('image_id').nth(1).describe().T[['mean', 'std']]

66011

                      mean           std
replay_id       275.000000      0.000000
image_id      33274.483753  19306.989967
num_anns          6.507688      2.578995
density           0.895423      0.073553
centeredness      0.839779      0.101048
mixture           0.271129      0.368852

In [31]:
print(len(df_score_vanilla_exploded.sort_values(['image_id'], ascending=[True]).groupby('image_id').nth(2)))
df_score_vanilla_exploded.sort_values(['image_id'], ascending=[True]).groupby('image_id').nth(2).describe().T[['mean', 'std']]

63908

                      mean           std
replay_id       275.000000      0.000000
image_id      33249.994664  19267.432024
num_anns          6.656021      2.485847
density           0.888192      0.077711
centeredness      0.834094      0.100568
mixture           0.222718      0.348722

In [32]:
df_score_kbrs_exploded.describe()

,replay_id,image_id,num_anns,density,centeredness,mixture
count,435517.0,435517.000000,435517.000000,435511.000000,435511.000000,435511.00000
mean,275.0,35653.099893,7.759337,0.898909,0.834536,0.25886
std,0.0,19435.635093,3.031661,0.069459,0.101638,0.36492
min,275.0,3.000000,0.000000,0.263184,0.216064,0.00000
25%,275.0,18964.000000,6.000000,0.861328,0.757812,0.00000
50%,275.0,36470.000000,7.000000,0.910156,0.850586,0.00000
75%,275.0,52892.000000,10.000000,0.948730,0.915039,0.56250
max,275.0,66687.000000,23.000000,1.000000,1.000000,1.00000

In [33]:
print(len(df_score_kbrs_exploded.sort_values(['image_id'], ascending=[True]).groupby('image_id').nth(0)))
df_score_kbrs_exploded.sort_values(['image_id'], ascending=[True]).groupby('image_id').nth(0).describe().T[['mean', 'std']]

66674

                      mean           std
replay_id       275.000000      0.000000
image_id      33345.886672  19251.909849
num_anns          6.531946      2.831619
density           0.913106      0.063970
centeredness      0.858527      0.101866
mixture           0.372598      0.399441

In [34]:
print(len(df_score_kbrs_exploded.sort_values(['image_id'], ascending=[True]).groupby('image_id').nth(1)))
df_score_kbrs_exploded.sort_values(['image_id'], ascending=[True]).groupby('image_id').nth(1).describe().T[['mean', 'std']]

66250

                      mean           std
replay_id       275.000000      0.000000
image_id      33309.695547  19281.211402
num_anns          6.567442      2.805561
density           0.906805      0.065060
centeredness      0.845850      0.101322
mixture           0.297415      0.370243

In [35]:
print(len(df_score_kbrs_exploded.sort_values(['image_id'], ascending=[True]).groupby('image_id').nth(2)))
df_score_kbrs_exploded.sort_values(['image_id'], ascending=[True]).groupby('image_id').nth(2).describe().T[['mean', 'std']]

63794

                      mean           std
replay_id       275.000000      0.000000
image_id      33440.370145  19362.013631
num_anns          6.743283      2.709267
density           0.896791      0.075602
centeredness      0.836506      0.103241
mixture           0.251212      0.357057

In [36]:
print(df_vanilla.head())

   id  image_id  category_id                bbox     score  area  \
0   1         3            1      [0, 0, 19, 12]  0.796460   228
1   2         3            1  [108, 114, 19, 12]  0.732251   228
2   3         4            1      [0, 0, 19, 12]  0.796460   228
3   4         4            1  [108, 114, 19, 12]  0.732251   228
4   5         5            1      [0, 0, 19, 12]  0.796460   228

                                 segmentation  iscrowd
0              [[0, 0, 19, 0, 19, 12, 0, 12]]        0
1  [[108, 114, 127, 114, 127, 126, 108, 126]]        0
2              [[0, 0, 19, 0, 19, 12, 0, 12]]        0
3  [[108, 114, 127, 114, 127, 126, 108, 126]]        0
4              [[0, 0, 19, 0, 19, 12, 0, 12]]        0

In [37]:
import pandas as pd
import numpy as np
from scipy.spatial.distance import cdist

def track_streaks(df, dist_threshold=10.0):
    # 1. 준비: x, y 추출 및 이미지 순서 정렬
    df['x'] = df['bbox'].apply(lambda b: b[0])
    df['y'] = df['bbox'].apply(lambda b: b[1])
    image_ids = sorted(df['image_id'].unique())
    
    # 결과 저장을 위한 컬럼
    df['streak_id'] = -1
    next_streak_id = 0
    
    # 첫 프레임 객체들에 ID 부여
    first_frame_idx = df[df['image_id'] == image_ids[0]].index
    for idx in first_frame_idx:
        df.at[idx, 'streak_id'] = next_streak_id
        next_streak_id += 1
        
    # 2. 프레임 순회하며 매칭
    for i in range(len(image_ids) - 1):
        curr_id = image_ids[i]
        next_id = image_ids[i+1]
        
        curr_rows = df[df['image_id'] == curr_id]
        next_rows = df[df['image_id'] == next_id]
        
        if curr_rows.empty or next_rows.empty:
            continue
            
        # 두 프레임 간의 모든 거리 계산 (Euclidean)
        curr_coords = curr_rows[['x', 'y']].values
        next_coords = next_rows[['x', 'y']].values
        dist_matrix = cdist(curr_coords, next_coords, metric='euclidean')
        
        # Greedy Matching
        matched_next_indices = []
        for curr_idx_in_matrix in range(len(curr_rows)):
            # 현재 객체에서 가장 가까운 다음 프레임 객체 찾기
            min_dist = dist_matrix[curr_idx_in_matrix].min()
            next_idx_in_matrix = dist_matrix[curr_idx_in_matrix].argmin()
            
            if min_dist < dist_threshold and next_idx_in_matrix not in matched_next_indices:
                # 매칭 성공: 이전 streak_id 계승
                actual_next_idx = next_rows.index[next_idx_in_matrix]
                actual_curr_idx = curr_rows.index[curr_idx_in_matrix]
                
                df.at[actual_next_idx, 'streak_id'] = df.at[actual_curr_idx, 'streak_id']
                matched_next_indices.append(next_idx_in_matrix)
        
        # 매칭되지 않은 다음 프레임 객체들은 새로운 Streak ID 부여
        for j, next_idx in enumerate(next_rows.index):
            if j not in matched_next_indices:
                df.at[next_idx, 'streak_id'] = next_streak_id
                next_streak_id += 1
                
    return df

In [38]:
# 실행
df_vanilla_tracked = track_streaks(df_vanilla, dist_threshold=15.0)

# Streak 길이(지속성) 측정
streak_lengths = df_vanilla_tracked.groupby('streak_id').size()
print(streak_lengths)

streak_id
0        3021
1        2514
2          11
3         116
4          44
         ...
30442       9
30443       1
30444       8
30445       1
30446       1
Length: 30447, dtype: int64

In [39]:
# 1. 각 Streak ID별로 포함된 데이터(프레임) 개수 카운트
vanilla_streak_counts = df_vanilla_tracked.groupby('streak_id').size()

# 2. 전체 Streak의 평균 지속 프레임 수 계산
average_vanilla_streak_length = vanilla_streak_counts.mean()

print(f"평균 Streak 지속 프레임: {average_vanilla_streak_length:.2f} frames")

평균 Streak 지속 프레임: 14.18 frames

In [40]:
long_vanilla_streaks = vanilla_streak_counts[vanilla_streak_counts >= 24]
avg_long_vanilla_streak = long_vanilla_streaks.mean()

print(f"24프레임 이상 유지된 Streak의 평균: {avg_long_vanilla_streak:.2f} frames")

24프레임 이상 유지된 Streak의 평균: 83.84 frames

In [41]:
df_vanilla_tracked

,id,image_id,category_id,bbox,score,area,segmentation,iscrowd,x,y,streak_id
0,1,3,1,"[0, 0, 19, 12]",0.796460,228,"[[0, 0, 19, 0, 19, 12, 0, 12]]",0,0,0,0
1,2,3,1,"[108, 114, 19, 12]",0.732251,228,"[[108, 114, 127, 114, 127, 126, 108, 126]]",0,108,114,1
2,3,4,1,"[0, 0, 19, 12]",0.796460,228,"[[0, 0, 19, 0, 19, 12, 0, 12]]",0,0,0,0
3,4,4,1,"[108, 114, 19, 12]",0.732251,228,"[[108, 114, 127, 114, 127, 126, 108, 126]]",0,108,114,1
4,5,5,1,"[0, 0, 19, 12]",0.796460,228,"[[0, 0, 19, 0, 19, 12, 0, 12]]",0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
431784,431785,66687,1,"[15, 111, 20, 11]",0.725220,220,"[[15, 111, 35, 111, 35, 122, 15, 122]]",0,15,111,30440
431785,431786,66687,1,"[50, 0, 20, 11]",0.710864,220,"[[50, 0, 70, 0, 70, 11, 50, 11]]",0,50,0,28896
431786,431787,66687,1,"[0, 114, 19, 11]",0.631751,209,"[[0, 114, 19, 114, 19, 125, 0, 125]]",0,0,114,30418
431787,431788,66687,1,"[3, 66, 20, 12]",0.558392,240,"[[3, 66, 23, 66, 23, 78, 3, 78]]",0,3,66,30436
431788,431789,66687,1,"[20, 109, 20, 12]",0.512251,240,"[[20, 109, 40, 109, 40, 121, 20, 121]]",0,20,109,30442

In [42]:
df_vanilla_tracked[df_vanilla_tracked['streak_id'] == 0]

,id,image_id,category_id,bbox,score,area,segmentation,iscrowd,x,y,streak_id
0,1,3,1,"[0, 0, 19, 12]",0.796460,228,"[[0, 0, 19, 0, 19, 12, 0, 12]]",0,0,0,0
2,3,4,1,"[0, 0, 19, 12]",0.796460,228,"[[0, 0, 19, 0, 19, 12, 0, 12]]",0,0,0,0
4,5,5,1,"[0, 0, 19, 12]",0.796460,228,"[[0, 0, 19, 0, 19, 12, 0, 12]]",0,0,0,0
6,7,6,1,"[0, 0, 19, 12]",0.796460,228,"[[0, 0, 19, 0, 19, 12, 0, 12]]",0,0,0,0
8,9,7,1,"[0, 0, 19, 12]",0.796460,228,"[[0, 0, 19, 0, 19, 12, 0, 12]]",0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
12417,12418,3019,1,"[0, 1, 20, 12]",0.935188,240,"[[0, 1, 20, 1, 20, 13, 0, 13]]",0,0,1,0
12425,12426,3020,1,"[0, 3, 19, 12]",0.955998,228,"[[0, 3, 19, 3, 19, 15, 0, 15]]",0,0,3,0
12432,12433,3021,1,"[0, 3, 20, 12]",0.962569,240,"[[0, 3, 20, 3, 20, 15, 0, 15]]",0,0,3,0
12439,12440,3022,1,"[0, 3, 20, 12]",0.937492,240,"[[0, 3, 20, 3, 20, 15, 0, 15]]",0,0,3,0
12447,12448,3023,1,"[0, 5, 20, 12]",0.855499,240,"[[0, 5, 20, 5, 20, 17, 0, 17]]",0,0,5,0

In [47]:
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from ipywidgets import interact, IntSlider

def interactive_rank_viewer(df_tracked, grid_size=128):
    # 1. 프레임별로 Score 순위(Rank) 계산 (내림차순: 점수 높은 것이 1등)
    # method='first'를 사용하면 점수가 같더라도 중복 순위 없이 1, 2등을 나눕니다.
    df_tracked['rank'] = df_tracked.groupby('image_id')['score'].rank(ascending=False, method='first').astype(int)
    
    frame_list = sorted(df_tracked['image_id'].unique())
    
    # Streak ID별 고유 색상은 유지 (객체 추적 연속성 확인용)
    all_streak_ids = df_tracked['streak_id'].unique()
    cmap = plt.cm.get_cmap('tab20', 20)
    streak_colors = {sid: cmap(i % 20) for i, sid in enumerate(all_streak_ids)}
    streak_colors[-1] = (0.5, 0.5, 0.5, 1)

    def plot_frame(frame_id):
        fig, ax = plt.subplots(figsize=(10, 10))
        
        ax.set_xlim(0, grid_size)
        ax.set_ylim(0, grid_size)
        ax.invert_yaxis()
        ax.set_aspect('equal')
        ax.grid(True, linestyle=':', alpha=0.5)
        
        now_df = df_tracked[df_tracked['image_id'] == frame_id].copy()
    
        # [핵심] Rank를 기준으로 내림차순 정렬 (예: 5위 -> 4위 -> ... -> 1위 순서로 그리기)
        # 이렇게 하면 1위(Rank 1)가 가장 마지막에 그려져서 최상단에 위치하게 됩니다.
        now_df = now_df.sort_values(by='rank', ascending=False)
    
        for _, row in now_df.iterrows():
            sid = row['streak_id']
            score = row['score']
            rank = row['rank']
            color = streak_colors[sid]
            
            # 1위인 경우 테두리를 더 굵게 표현하여 강조할 수도 있습니다.
            edge_width = 3 if rank == 1 else 1.5
            
            rect = patches.Rectangle(
                (row['x'], row['y']), 20, 12,
                linewidth=edge_width,
                edgecolor=color,
                facecolor=color,
                alpha=0.4, # 겹침 확인을 위해 투명도 유지
                zorder=3 + (100 / rank) # zorder를 이용해 명시적으로 레이어 순서 지정 가능
            )
            ax.add_patch(rect)
            
            # 라벨 표시
            label_text = f"Rank: {rank}\n{score:.4f}"
            ax.text(
                row['x'], row['y'] - 2, 
                label_text, 
                color='white', fontsize=8, fontweight='bold',
                bbox=dict(facecolor=color, alpha=0.8, edgecolor='none', pad=2),
                zorder=4 + (100 / rank) # 텍스트도 사각형 위에 오도록 zorder 설정
            )
    
        plt.show()

    interact(plot_frame, 
             frame_id=IntSlider(min=min(frame_list), max=max(frame_list), 
                                step=1, value=min(frame_list),
                                description='Frame:'))

# 실행 전 데이터프레임에 x, y가 있는지 확인하세요!
interactive_rank_viewer(df_vanilla_tracked)

/tmp/ipykernel_204328/1009701952.py:14: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed in 3.11. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap()`` or ``pyplot.get_cmap()`` instead.
  cmap = plt.cm.get_cmap('tab20', 20)

interactive(children=(IntSlider(value=3, description='Frame:', max=66687, min=3), Output()), _dom_classes=('wi…